# GET request to fetch all users
GET http://localhost:3000/api/users

###

# POST request to add a new user
POST http://localhost:3000/api/users
Content-Type: application/json

{
    "name": "Alice"
}
